### ISSUE TITLE
增加这些信息

### ISSUE THREAD

**Issue by godspeed-w** [TP-Lab/EOS-Navigator#3]
EOS空投信息平台 (EOS Drop)

eosdrops: [https://eosdrops.io/](url)

airdropsforeos: [https://airdropsforeos.com/](url)

horuspay:  [https://horuspay.io/](url)

EOS交易所 (EOS Exchange)

Bithumb: [https://www.bithumb.com/](url)

Huobi: [https://www.huobi.pro/ko-kr/eos_usdt/exchange/](url)

Bitfinex: (https://www.bitfinex.com/t/EOS:USD](url)

Binance: [https://www.binance.com/trade.html?symbol=EOS_BTC](url)

HitBTC: [https://hitbtc.com/exchange/EOS-to-USDT](url)

EOS核心文档 (Eos core document)

WhitePaper: [https://github.com/EOSIO/Documentation/blob/master/TechnicalWhitePaper.md](url) （技术白皮书）

wiki: [https://github.com/EOSIO/eos/wiki](url) (wiki)

automated build script: [https://github.com/EOSIO/eos#automated-build-script](url) (技术文档)

EOS媒体 (EOS Media)

helloeos: [https://www.helloeos.one/](url)

huoxing24: [http://www.huoxing24.com/](url)

lianjinshu: [http://www.lianjinshu.com/](url)

dayqkl: [http://www.dayqkl.com/](url)

bishijie: [http://www.bishijie.com/kuaixun/](url)

biiquan: [http://www.biiquan.com/](url)

 其他（Others）

EOS公钥私钥生成器: [https://eos-key.mytokenpocket.vip/](url)

**Comment by chendatony31** [comment]
horuspay: https://horuspay.io/ 这一条实在没看出来哪里跟 空投有关系 ，其他都已添加
